version: '3.8'

services:
  db:
    image: postgres:18
    container_name: insurance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: insurance_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  
      - ./database/migrations:/docker-entrypoint-initdb.d  

volumes:
  postgres_data: